dependencies:
- name: croc-hunter-jenkinsx
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.37
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
